medical/urls.py
# Copyright (c) 2012-2026 Jose Antonio Chavarría <jachavar@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

__author__ = "Jose Antonio Chavarría"
__license__ = "GPLv3"

from django.urls import re_path, reverse_lazy
from django.views.generic import RedirectView

from .views import (
    HistoryAntecedentsCreate,
    HistoryAntecedentsDetail,
    HistoryAntecedentsUpdate,
    HistoryList,
    PatientCreate,
    PatientDelete,
    PatientDetail,
    PatientListView,
    PatientMedicalReport,
    PatientRedirectDetail,
    PatientRelatives,
    PatientSearch,
    PatientTests,
    PatientUpdate,
    ProblemConnections,
    ProblemCreate,
    ProblemDelete,
    ProblemDetail,
    ProblemList,
    ProblemSearch,
    ProblemTestDelete,
    ProblemTests,
    ProblemUpdate,
)

urlpatterns = [
    re_path(
        r"^$",
        RedirectView.as_view(url=reverse_lazy("patient_list"), permanent=True),
        name="medical_records",
    ),
    re_path(
        r"^patient/$",
        PatientListView.as_view(),
        name="patient_list",
    ),
    re_path(
        r"^patient/search/$",
        PatientSearch.as_view(),
        name="patient_search",
    ),
    re_path(
        r"^patient/add/$",
        PatientCreate.as_view(),
        name="patient_add",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)/change/$",
        PatientUpdate.as_view(),
        name="patient_change",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)/delete/$",
        PatientDelete.as_view(),
        name="patient_delete",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)/$",
        PatientRedirectDetail.as_view(),
        name="patient_redirect_detail",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)-(?P<slug>[-\w]+)/$",
        PatientDetail.as_view(),
        name="patient_detail",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)/report/$",
        PatientMedicalReport.as_view(),
        name="patient_medical_report",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)/relatives/$",
        PatientRelatives.as_view(),
        name="patient_relatives",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)/tests/$",
        PatientTests.as_view(),
        name="patient_tests",
    ),
    re_path(
        r"^problem/search/$",
        ProblemSearch.as_view(),
        name="problem_search",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)/problem/$",
        ProblemList.as_view(),
        name="problem_list",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)/problem/add/$",
        ProblemCreate.as_view(),
        name="problem_add",
    ),
    re_path(
        r"^problem/(?P<pk>\d+)/change/$",
        ProblemUpdate.as_view(),
        name="problem_change",
    ),
    re_path(
        r"^problem/(?P<pk>\d+)/$",
        ProblemDetail.as_view(),
        name="problem_detail",
    ),
    re_path(
        r"^problem/(?P<pk>\d+)/delete/$",
        ProblemDelete.as_view(),
        name="problem_delete",
    ),
    re_path(
        r"^problem/(?P<pk>\d+)/connections/$",
        ProblemConnections.as_view(),
        name="problem_connections",
    ),
    re_path(
        r"^problem/(?P<pk>\d+)/tests/$",
        ProblemTests.as_view(),
        name="problem_tests",
    ),
    re_path(
        r"^test/(?P<pk>\d+)/delete/$",
        ProblemTestDelete.as_view(),
        name="problem_test_delete",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)/history/$",
        HistoryList.as_view(),
        name="patient_history",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)/history/antecedents/$",
        HistoryAntecedentsDetail.as_view(),
        name="patient_history_antecedents",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)/history/antecedents/add/$",
        HistoryAntecedentsCreate.as_view(),
        name="patient_history_antecedents_add",
    ),
    re_path(
        r"^patient/(?P<pk>\d+)/history/antecedents/change/$",
        HistoryAntecedentsUpdate.as_view(),
        name="patient_history_antecedents_change",
    ),
]

medical/models/problem.py
# Copyright (c) 2012-2026 Jose Antonio Chavarría <jachavar@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

__author__ = "Jose Antonio Chavarría"
__license__ = "GPLv3"

from django.db import models
from django.utils.translation import gettext_lazy as _

from . import TimeStampedModel


class OpenedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(closing_date__isnull=True)


class ClosedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(closing_date__isnull=False)


class Problem(TimeStampedModel):
    order_number = models.PositiveSmallIntegerField(verbose_name=_("order number"))
    closing_date = models.DateField(
        blank=True, null=True, editable=False, verbose_name=_("closing date")
    )

    meeting_place = models.CharField(
        max_length=50, null=True, blank=True, verbose_name=_("meeting place")
    )

    wording = models.TextField(verbose_name=_("wording"))

    subjetive = models.TextField(null=True, blank=True, verbose_name=_("subjetive"))
    objetive = models.TextField(null=True, blank=True, verbose_name=_("objetive"))
    appreciation = models.TextField(
        null=True, blank=True, verbose_name=_("appreciation")
    )
    action_plan = models.TextField(null=True, blank=True, verbose_name=_("action plan"))
    prescription = models.TextField(
        null=True, blank=True, verbose_name=_("doctor's orders")
    )

    patient = models.ForeignKey("Patient", on_delete=models.CASCADE)

    doctor = models.ForeignKey(
        "medical.Staff",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_("attending physician"),
    )

    connections = models.ManyToManyField("self", blank=True)

    objects = models.Manager()
    opened = OpenedManager()
    closed = ClosedManager()

    class Meta:
        app_label = "medical"
        db_table = "problem"
        ordering = ["order_number"]
        verbose_name = _("Medical Problem")
        verbose_name_plural = _("Medical Problems")
        indexes = [
            models.Index(fields=["patient", "order_number"]),
            models.Index(fields=["closing_date", "modified"]),
        ]

    def __str__(self):
        return f"{self.order_number}: {self.wording}"

    @staticmethod
    def get_last_order_number(patient_id):
        last_order_number = Problem.objects.filter(
            patient_id__exact=patient_id
        ).aggregate(models.Max("order_number"))["order_number__max"]
        if not last_order_number:
            last_order_number = 0

        return last_order_number

medical/models/test.py
# Copyright (c) 2012-2026 Jose Antonio Chavarría <jachavar@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

__author__ = "Jose Antonio Chavarría"
__license__ = "GPLv3"

import os

from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.utils.translation import gettext_lazy as _

from . import TimeStampedModel


class Test(TimeStampedModel):
    document_type = models.CharField(
        max_length=128, null=True, blank=True, verbose_name=_("MIME type")
    )
    document = models.FileField(
        upload_to="medical_tests/%Y/%m/%d", verbose_name=_("document")
    )

    problem = models.ForeignKey("Problem", on_delete=models.CASCADE)

    class Meta:
        app_label = "medical"
        indexes = [
            models.Index(fields=["problem"]),
        ]

    def __str__(self):
        return str(self.document)

    def filename(self):
        return os.path.basename(self.document.name)


@receiver(pre_delete, sender=Test)
def test_delete(sender, instance, **kwargs):
    instance.document.delete(False)

medical/models/time_stamped.py
# -*- coding: UTF-8 -*-

from django.db import models


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating
    "created" and "modified" fields.
    """

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

medical/views/base.py
# Copyright (c) 2012-2026 Jose Antonio Chavarría <jachavar@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

"""
Base imports and utilities for medical views.
This module contains common imports used across all view modules.
"""

import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    RedirectView,
    UpdateView,
)
from el_pagination.views import AjaxListView

logger = logging.getLogger(__name__)


class PatientContextMixin:
    """Mixin to add patient to context based on pk in URL kwargs."""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        from medical.models import Patient

        context["patient"] = get_object_or_404(
            Patient, pk=self.kwargs.get("pk") or self.object.patient.id
        )
        return context


class SuccessMessageMixin:
    """Mixin providing success message and redirect after form submission."""

    success_message = ""
    success_url_name = ""

    def get_success_url(self):
        messages.success(self.request, self.success_message % self.object)
        return reverse(self.success_url_name, args=(self.object.id,))


class DeleteConfirmationMixin:
    """Mixin providing title and cancel_url for delete confirmation templates."""

    title_prefix = ""
    cancel_url_name = ""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"{self.title_prefix}: {self.object}"
        context["cancel_url"] = reverse(self.cancel_url_name, args=(self.object.id,))
        return context


class ProblemClosingMixin:
    """Mixin handling problem closing logic in form_valid."""

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.closing_date = timezone.now() if form.cleaned_data["closed"] else None
        instance.save()
        return super().form_valid(form)

medical/views/history_views.py
# Copyright (c) 2012-2026 Jose Antonio Chavarría <jachavar@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

"""History-related views."""

from django.http import Http404

from ..forms import HistoryAntecedentsForm
from ..models import History, Patient, Problem
from .base import (
    AjaxListView,
    CreateView,
    DetailView,
    LoginRequiredMixin,
    UpdateView,
    _,
    get_object_or_404,
    messages,
    redirect,
    reverse,
)


class HistoryList(LoginRequiredMixin, AjaxListView):
    model = Problem
    template_name = "history_list.html"
    page_template = "includes/problem_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["patient"] = get_object_or_404(Patient, pk=self.kwargs["pk"])

        return context

    def get_queryset(self):
        super().get_queryset()
        # Optimizado: select_related para evitar consultas N+1
        return (
            Problem.closed.filter(patient__id=self.kwargs["pk"])
            .select_related("patient", "doctor")
            .order_by("-modified")
        )


class HistoryAntecedentsDetail(LoginRequiredMixin, DetailView):
    model = History
    context_object_name = "history"
    template_name = "history_antecedents_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        patient = get_object_or_404(Patient, pk=self.kwargs["pk"])
        history = get_object_or_404(History, patient__id=self.kwargs["pk"])

        context["patient"] = patient
        context["history"] = history

        return context

    def get_queryset(self):
        return History.objects.filter(patient__id=self.kwargs["pk"]).select_related(
            "patient"
        )

    def get(self, request, *args, **kwargs):
        try:
            return super().get(request, *args, **kwargs)
        except Http404:
            # Verificar que el paciente existe primero
            get_object_or_404(Patient, pk=self.kwargs["pk"])
            # Paciente existe pero history no - redirigir a creación
            return redirect("patient_history_antecedents_add", pk=self.kwargs["pk"])


class HistoryAntecedentsCreate(LoginRequiredMixin, CreateView):
    model = History
    form_class = HistoryAntecedentsForm
    template_name = "history_antecedents_form.html"

    def get_initial(self):
        return {
            "patient": self.kwargs["pk"],
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        patient = get_object_or_404(Patient, pk=self.kwargs["pk"])
        context["title"] = f"{patient} ({_('Update antecedents')})"
        context["patient"] = patient

        return context

    def get_success_url(self):
        messages.success(self.request, _("Antecedents have been updated!"))

        return reverse("patient_history_antecedents", args=(self.object.patient.id,))


class HistoryAntecedentsUpdate(LoginRequiredMixin, UpdateView):
    model = History
    form_class = HistoryAntecedentsForm
    template_name = "history_antecedents_form.html"

    def get_initial(self):
        return {
            "patient": self.kwargs["pk"],
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        patient = get_object_or_404(Patient, pk=self.kwargs["pk"])
        context["title"] = f"{patient} ({_('Update antecedents')})"
        context["patient"] = patient

        return context

    def get_object(self, queryset=None):
        # Optimizado: select_related para cargar patient
        return History.objects.select_related("patient").get(
            patient__id=self.kwargs["pk"]
        )

    def get_success_url(self):
        messages.success(self.request, _("Antecedents have been updated!"))

        return reverse("patient_history_antecedents", args=(self.object.patient.id,))

medical/templates/includes/history_antecedents_detail.html
{% load i18n %}

{% if history %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{% trans 'Personal antecedents' %}</h2>
        </div>
        <div class="panel-body">
            {% if history.medical_intolerance %}
                <p>{% trans 'medical intolerance'|capfirst %}: <strong>{{ history.medical_intolerance }}</strong></p>
            {% endif %}

            {% if history.birth_growth %}
                <p>{% trans 'birth and growth'|capfirst %}: <strong>{{ history.birth_growth }}</strong></p>
            {% endif %}

            {% if history.growth_sexuality %}
                <p>{% trans 'growth and sexuality'|capfirst %}: <strong>{{ history.growth_sexuality }}</strong></p>
            {% endif %}

            {% if history.feed %}
                <p>{% trans 'feed'|capfirst %}: <strong>{{ history.feed }}</strong></p>
            {% endif %}

            {% if history.habits %}
                <p>{% trans 'habits'|capfirst %}: <strong>{{ history.habits }}</strong></p>
            {% endif %}

            {% if history.peristaltic_conditions %}
                <p>{% trans 'peristaltic conditions'|capfirst %}: <strong>{{ history.peristaltic_conditions }}</strong></p>
            {% endif %}

            {% if history.psychological_conditions %}
                <p>{% trans 'psychological conditions'|capfirst %}: <strong>{{ history.psychological_conditions }}</strong></p>
            {% endif %}

            {% if history.children_complaint %}
                <p>{% trans 'children complaint'|capfirst %}: <strong>{{ history.children_complaint }}</strong></p>
            {% endif %}

            {% if history.veneral_disease %}
                <p>{% trans 'veneral disease'|capfirst %}: <strong>{{ history.veneral_disease }}</strong></p>
            {% endif %}

            {% if history.accident_surgical_operation %}
                <p>{% trans 'accidents and surgical operations'|capfirst %}: <strong>{{ history.accident_surgical_operation }}</strong></p>
            {% endif %}

            {% if history.mental_illness %}
                <p>{% trans 'mental illness'|capfirst %}: <strong>{{ history.mental_illness }}</strong></p>
            {% endif %}
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{% trans 'Family antecedents' %}</h2>
        </div>
        <div class="panel-body">
            {% if history.parents_status_health %}
                <p>{% trans 'parents status health'|capfirst %}: <strong>{{ history.parents_status_health }}</strong></p>
            {% endif %}

            {% if history.brothers_status_health %}
                <p>{% trans 'brothers status health'|capfirst %}: <strong>{{ history.brothers_status_health }}</strong></p>
            {% endif %}

            {% if history.spouse_childs_status_health %}
                <p>{% trans 'spouse and childs status health'|capfirst %}: <strong>{{ history.spouse_childs_status_health }}</strong></p>
            {% endif %}

            {% if history.family_illness %}
                <p>{% trans 'family illness'|capfirst %}: <strong>{{ history.family_illness }}</strong></p>
            {% endif %}
        </div>
    </div>
{% endif %}

medical/templates/includes/patient_actions.html
{% load i18n static %}

<ul role="menu" class="patient-actions">
    <li>
        <a href="{% url 'patient_change' patient.id %}" title="{% trans 'Update social data' %}">
            <span class="fa fa-edit"></span> <span class="sr-only">{% trans 'Update' %}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'patient_relatives' patient.id %}" title="{% trans 'Relatives' %}">
            <span class="fa fa-users"></span> <span class="sr-only">{% trans 'Relatives' %}</span>
            <span class="badge">{{ patient.relatives.count }}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'problem_list' patient.id %}" title="{% trans 'Medical problems report' %}">
            <span class="fa fa-user-md"></span> <span class="sr-only">{% trans 'Medical problems report' %}</span>
            <span class="badge">{{ patient.problem_set.count }}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'patient_tests' patient.id %}" title="{% trans 'Medical tests' %}">
            <span class="fa fa-heartbeat"></span> <span class="sr-only">{% trans 'Medical tests' %}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'patient_history' patient.id %}" title="{% trans 'Clinic history' %}">
            <span class="fa fa-ambulance"></span> <span class="sr-only">{% trans 'Clinic history' %}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'patient_medical_report' patient.id %}" title="{% trans 'Print medical report' %}">
            <span class="fa fa-print"></span> <span class="sr-only">{% trans 'Print medical report' %}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'patient_delete' patient.id %}" title="{% trans 'Delete patient' %}" class="btn btn-danger">
            <span class="fa fa-trash-o"></span> <span class="sr-only">{% trans 'Delete patient' %}</span>
        </a>
    </li>
</ul>

medical/templates/includes/patient_detail.html
{% load i18n static %}

{% if patient.doctor_assigned or patient.race or patient.gender or patient.age or patient.birth_place %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{% trans 'Basic data' %}</h2>
        </div>
        <div class="panel-body">
        {% if patient.doctor_assigned %}
            <p>{% trans 'doctor allocated by quota'|capfirst %}: <strong>{{ patient.doctor_assigned }}</strong></p>
        {% endif %}

        {% if patient.race %}
            <p>{% trans 'race'|capfirst %}: <strong>{{ patient.race }}</strong></p>
        {% endif %}

        {% if patient.gender %}
            <p>{% trans 'gender'|capfirst %}: <strong>{{ patient.gender_description }}</strong></p>
        {% endif %}

        {% if patient.birth_place %}
            <p>{% trans 'birth place'|capfirst %}: <strong>{{ patient.birth_place }}</strong></p>
        {% endif %}

        {% if patient.age %}
            <p>{% trans 'Age' %}: <strong>{{ patient.birth_date|timesince }}</strong></p>
            <p>{% trans 'birth date'|capfirst %}: <strong>{{ patient.birth_date|date:'Y-m-d' }}</strong></p>
            {% if patient.decease_date %}
                <p class="label label-danger">{% trans 'decease date'|capfirst %}: <strong>{{ patient.decease_date|date:'Y-m-d' }}</strong></p>
            {% endif %}
        {% endif %}
        </div>

        <div class="panel-footer text-center">
            {% include 'includes/patient_actions.html' %}
        </div>
    </div>
{% endif %}

{% if patient.address or patient.phone_contact or patient.tin or patient.ssn or patient.health_card_number or patient.insurance_company %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{% trans 'Administrative data' %}</h2>
        </div>
        <div class="panel-body">
        {% if patient.address %}
            <p>{% trans 'address'|capfirst %}: <strong>{{ patient.address }}</strong></p>
        {% endif %}

        {% if patient.phone_contact %}
            <p>{% trans 'phone contact'|capfirst %}: <strong>{{ patient.phone_contact }}</strong></p>
        {% endif %}

        {% if patient.tin %}
            <p>{% trans 'taxpayer Identification Number (TIN)'|capfirst %}: <strong>{{ patient.tin }}</strong></p>
        {% endif %}

        {% if patient.ssn %}
            <p>{% trans 'social Security Number (SSN)'|capfirst %}: <strong>{{ patient.ssn }}</strong></p>
        {% endif %}

        {% if patient.health_card_number %}
            <p>{% trans 'health card number'|capfirst %}: <strong>{{ patient.health_card_number }}</strong></p>
        {% endif %}

        {% if patient.insurance_company %}
            <p>{% trans 'insurance company'|capfirst %}: <strong>{{ patient.insurance_company }}</strong></p>
        {% endif %}
        </div>
    </div>
{% endif %}

{% if patient.family_situation or patient.labour_situation or patient.education %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{% trans 'Extra data' %}</h2>
        </div>
        <div class="panel-body">
        {% if patient.family_situation %}
            <p>{% trans 'family situation'|capfirst %}: <strong>{{ patient.family_situation }}</strong></p>
        {% endif %}

        {% if patient.labour_situation %}
            <p>{% trans 'labour situation'|capfirst %}: <strong>{{ patient.labour_situation }}</strong></p>
        {% endif %}

        {% if patient.education %}
            <p>{% trans 'education'|capfirst %}: <strong>{{ patient.education }}</strong></p>
        {% endif %}
        </div>
    </div>
{% endif %}

medical/templates/includes/patient_info.html
{% load i18n %}

{% if patient %}
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    {% if forloop %}
                    <div class="col-xs-2 text-right">
                        {{ forloop.counter0|add:pages.current_start_index }}.
                    </div>
                    {% endif %}
                    <div class="col-xs-10">
                        <a href="{% url 'patient_detail' patient.id patient|slugify %}">{{ patient }}</a>
                        {% if patient.gender %}
                            <br />
                            {% trans 'gender'|capfirst %}: {{ patient.gender_description }}
                        {% endif %}
                        {% if patient.age %}
                            <br />
                            {% trans 'Age' %}: {{ patient.birth_date|timesince }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="panel-footer text-center">
                {% include 'includes/patient_actions.html' %}
            </div>
        </div>
    </div>
{% endif %}

medical/templates/includes/patient_list.html
{% load i18n %}
{% load el_pagination_tags %}

{% paginate object_list %}
{% get_pages %}

{% for patient in object_list %}
    {% include 'includes/patient_info.html' %}
{% empty %}
    <p class="alert alert-warning">{%trans 'No patients found.' %}</p>
{% endfor %}

{% show_more %}

medical/templates/includes/problem_actions.html
{% load i18n static %}

<ul role="menu" class="patient-actions">
    <li>
        <a href="{% url 'problem_change' problem.id %}" title="{% trans 'Update' %}">
            <span class="fa fa-edit"></span> <span class="sr-only">{% trans 'Update' %}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'problem_tests' problem.id %}" title="{% trans 'Medical tests' %}">
            <span class="fa fa-heartbeat"></span> <span class="sr-only">{% trans 'Medical tests' %}</span>
            <span class="badge">{{ problem.test_set.count }}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'problem_connections' problem.id %}" title="{% trans 'Connections' %}">
            <span class="fa fa-chain"></span> <span class="sr-only">{% trans 'Connections' %}</span>
            <span class="badge">{{ problem.connections.count }}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'problem_delete' problem.id %}" title="{% trans 'Delete medical problem' %}" class="btn btn-danger">
            <span class="fa fa-trash-o"></span> <span class="sr-only">{% trans 'Delete medical problem' %}</span>
        </a>
    </li>
</ul>

medical/templates/includes/problem_list.html
{% load i18n %}
{% load el_pagination_tags %}

{% paginate object_list %}
{% get_pages %}

{% for problem in object_list %}
    {% include 'includes/problem_info.html' %}
{% empty %}
    <p class="alert alert-warning">{%trans 'No medical problems found.' %}</p>
{% endfor %}

{% show_more %}

medical/templates/includes/test_actions.html
{% load i18n %}

<ul role="menu" class="patient-actions">
    <li>
        <a href="{{ test.document.url }}" title="{% trans 'View' %}"><span class="fa fa-eye"></span> <span class="sr-only">{% trans 'View' %}</span></a>
    </li>
    <li>
        <a href="{% url 'problem_test_delete' test.id %}" title="{% trans 'Delete test' %}" class="btn btn-danger"><span class="fa fa-trash-o"></span> <span class="sr-only">{% trans 'Delete test' %}</span></a>
    </li>
</ul>